/**
 * Scans src/assets/gallery/<ALBUM>/ for media and writes a generated
 * TypeScript module (src/generated/gallery-media.ts) that statically imports
 * every image so Next.js can optimize them at build time.
 *
 * Usage:
 *   pnpm gallery:generate
 *
 * To add a new album: drop a folder with its images into src/assets/gallery,
 * run this script, then add matching title/description overrides in
 * src/data/gallery.ts. No UI changes are required.
 */
import { execSync } from "node:child_process";
import { mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(scriptDir, "..");
const GALLERY_DIR = join(ROOT, "src", "assets", "gallery");
const OUT_FILE = join(ROOT, "src", "generated", "gallery-media.ts");

const IMAGE_EXT = /\.(jpe?g|png|webp|avif|gif)$/i;

const slugify = (value) =>
  value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const folders = readdirSync(GALLERY_DIR)
  .filter((name) => statSync(join(GALLERY_DIR, name)).isDirectory())
  .sort((a, b) => a.localeCompare(b));

let fileIndex = 0;
const imports = [];
const entries = [];
const albumTitles = [];

for (const folder of folders) {
  const files = readdirSync(join(GALLERY_DIR, folder))
    .filter((file) => IMAGE_EXT.test(file))
    .sort((a, b) => a.localeCompare(b));

  const mediaRefs = files.map((file) => {
    const name = `media${fileIndex++}`;
    imports.push(`import ${name} from "@/assets/gallery/${folder}/${file}";`);
    return name;
  });

  entries.push(
    `  ${JSON.stringify(slugify(folder))}: [${mediaRefs.join(", ")}],`,
  );
  albumTitles.push(
    `  ${JSON.stringify(slugify(folder))}: ${JSON.stringify(folder)},`,
  );
}

mkdirSync(dirname(OUT_FILE), { recursive: true });

const out = `/* This file is generated by scripts/generate-gallery.mjs (pnpm gallery:generate). */
/* Do not edit manually. */
import type { StaticImport } from "next/dist/shared/lib/get-img-props";

${imports.join("\n")}

export const galleryAlbumTitles: Record<string, string> = {
${albumTitles.join("\n")}
};

export const galleryMedia: Record<string, StaticImport[]> = {
${entries.join("\n")}
};
`;

writeFileSync(OUT_FILE, out);

execSync("pnpm exec biome check --write src/generated/gallery-media.ts", {
  cwd: ROOT,
  stdio: "inherit",
});

console.log(
  `Generated ${OUT_FILE} with ${entries.length} album(s) and ${fileIndex} media item(s).`,
);
